-- ============================================================================
-- Script 02: Table Definitions & Relational Constraints (3NF Normalized)
-- System: Tourism Booking MIS
-- PDB: PDB_32481_2025_TOURISM_BOOKING_DB
-- User: U_32481_2025_TOURISM_BOOKING_DB
-- ============================================================================

ALTER SESSION SET CONTAINER = PDB_32481_2025_TOURISM_BOOKING_DB;

-- Clean up existing objects for clean re-runs
DROP TABLE AUDIT_LOGS CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE BOOKING CASCADE CONSTRAINTS;
DROP TABLE TOUR_PACKAGE CASCADE CONSTRAINTS;
DROP TABLE TOURIST CASCADE CONSTRAINTS;
DROP TABLE PUBLIC_HOLIDAYS CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_TOURIST_ID;
DROP SEQUENCE SEQ_PACKAGE_ID;
DROP SEQUENCE SEQ_BOOKING_ID;
DROP SEQUENCE SEQ_PAYMENT_ID;

-- 1. Tourists Table
CREATE TABLE TOURIST (
    tourist_id        NUMBER(10)          PRIMARY KEY,
    first_name        VARCHAR2(50)        NOT NULL,
    last_name         VARCHAR2(50)        NOT NULL,
    email             VARCHAR2(100)       NOT NULL UNIQUE,
    phone_number      VARCHAR2(20)        NOT NULL,
    country           VARCHAR2(50)        NOT NULL,
    registration_date DATE DEFAULT SYSDATE NOT NULL
);

-- 2. Tour Packages Table
CREATE TABLE TOUR_PACKAGE (
    package_id        NUMBER(10)          PRIMARY KEY,
    package_name      VARCHAR2(100)       NOT NULL,
    destination       VARCHAR2(100)       NOT NULL,
    duration_days     NUMBER(3)           NOT NULL CHECK (duration_days > 0),
    price_per_person  NUMBER(10,2)        NOT NULL CHECK (price_per_person >= 0),
    max_capacity      NUMBER(5)           NOT NULL CHECK (max_capacity > 0)
);

-- 3. Bookings Table
CREATE TABLE BOOKING (
    booking_id        NUMBER(10)          PRIMARY KEY,
    tourist_id        NUMBER(10)          NOT NULL,
    package_id        NUMBER(10)          NOT NULL,
    booking_date      DATE DEFAULT SYSDATE NOT NULL,
    travel_date       DATE                NOT NULL,
    number_of_guests  NUMBER(3)           NOT NULL CHECK (number_of_guests > 0),
    total_amount      NUMBER(10,2)        NOT NULL CHECK (total_amount >= 0),
    booking_status    VARCHAR2(20)        DEFAULT 'PENDING' CHECK (booking_status IN ('PENDING', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT fk_booking_tourist FOREIGN KEY (tourist_id) REFERENCES TOURIST(tourist_id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_package FOREIGN KEY (package_id) REFERENCES TOUR_PACKAGE(package_id) ON DELETE CASCADE
);

-- 4. Payments Table
CREATE TABLE PAYMENT (
    payment_id        NUMBER(10)          PRIMARY KEY,
    booking_id        NUMBER(10)          NOT NULL UNIQUE,
    payment_date      DATE DEFAULT SYSDATE NOT NULL,
    amount_paid       NUMBER(10,2)        NOT NULL CHECK (amount_paid >= 0),
    payment_method    VARCHAR2(30)        NOT NULL CHECK (payment_method IN ('CREDIT_CARD', 'BANK_TRANSFER', 'MOBILE_MONEY', 'CASH')),
    payment_status    VARCHAR2(20)        DEFAULT 'COMPLETED' CHECK (payment_status IN ('COMPLETED', 'FAILED', 'REFUNDED')),
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES BOOKING(booking_id) ON DELETE CASCADE
);

-- 5. Public Holidays Reference Table (Used by day restriction trigger)
CREATE TABLE PUBLIC_HOLIDAYS (
    holiday_date      DATE                PRIMARY KEY,
    holiday_name      VARCHAR2(100)       NOT NULL
);

-- 6. Audit Trail Logs Table
CREATE TABLE AUDIT_LOGS (
    audit_id          NUMBER(10)          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name        VARCHAR2(50)        NOT NULL,
    operation_type    VARCHAR2(10)        NOT NULL,
    performed_by      VARCHAR2(50)        NOT NULL,
    performed_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    details           VARCHAR2(500)
);

-- Sequences
CREATE SEQUENCE SEQ_TOURIST_ID START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PACKAGE_ID START WITH 5001 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BOOKING_ID START WITH 8001 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAYMENT_ID START WITH 9001 INCREMENT BY 1;