-- ============================================================================
-- Script 04: DML Operations & Data Manipulation Showcase
-- System: Tourism Booking MIS
-- PDB: PDB_32481_2025_TOURISM_BOOKING_DB
-- User: U_32481_2025_TOURISM_BOOKING_DB
-- ============================================================================

ALTER SESSION SET CONTAINER = PDB_32481_2025_TOURISM_BOOKING_DB;
ALTER SESSION SET CURRENT_SCHEMA = U_32481_2025_TOURISM_BOOKING_DB;

-- ============================================================================
-- 1. INSERT OPERATIONS (New Registrations & Transactions)
-- ============================================================================

-- Register a new tourist
INSERT INTO TOURIST (tourist_id, first_name, last_name, email, phone_number, country, registration_date)
VALUES (SEQ_TOURIST_ID.NEXTVAL, 'Emmanuel', 'Nshimiyimana', 'e.nshimiye@example.rw', '+250788333444', 'Rwanda', SYSDATE);

-- Process a new booking for Emmanuel (Tourist 1006) for Akagera Safari (Package 5002)
INSERT INTO BOOKING (booking_id, tourist_id, package_id, booking_date, travel_date, number_of_guests, total_amount, booking_status)
VALUES (SEQ_BOOKING_ID.NEXTVAL, 1006, 5002, SYSDATE, SYSDATE + 20, 2, 1000.00, 'PENDING');

-- Process payment for the new booking (Booking 8006)
INSERT INTO PAYMENT (payment_id, booking_id, payment_date, amount_paid, payment_method, payment_status)
VALUES (SEQ_PAYMENT_ID.NEXTVAL, 8006, SYSDATE, 1000.00, 'MOBILE_MONEY', 'COMPLETED');

COMMIT;

-- ============================================================================
-- 2. UPDATE OPERATIONS (Status Updates & Adjustments)
-- ============================================================================

-- A. Confirm pending booking 8006 after successful payment
-- (Fires TRG_AUDIT_BOOKING_CHANGES update audit)
UPDATE BOOKING
SET booking_status = 'CONFIRMED'
WHERE booking_id = 8006;

-- B. Update David Kramer's (Booking 8003) travel date due to flight rescheduling
UPDATE BOOKING
SET travel_date = SYSDATE + 35
WHERE booking_id = 8003;

-- C. Apply a 10% promotional discount to high-capacity packages (Price adjustment)
-- Note: Requires trigger TRG_RESTRICT_DML_SCHEDULE to be disabled if executed on a weekday
ALTER TRIGGER TRG_RESTRICT_DML_SCHEDULE DISABLE;

UPDATE TOUR_PACKAGE
SET price_per_person = price_per_person * 0.90
WHERE max_capacity >= 30;

ALTER TRIGGER TRG_RESTRICT_DML_SCHEDULE ENABLE;

COMMIT;

-- ============================================================================
-- 3. DELETE OPERATIONS (Cancellations & Cleanup)
-- ============================================================================

-- Remove failed or refunded payment record for cancelled booking (Booking 8005)
-- Note: Cascade constraints allow deleting payments safely
DELETE FROM PAYMENT
WHERE booking_id = 8005 AND payment_status = 'FAILED';

-- Remove inactive tourist registration who has no bookings
DELETE FROM TOURIST
WHERE email = 'claire.d@france-travel.fr' 
  AND tourist_id NOT IN (SELECT DISTINCT tourist_id FROM BOOKING WHERE booking_status != 'CANCELLED');

COMMIT;

-- ============================================================================
-- 4. DQL QUERIES (Data Retrieval & Analytical Views)
-- ============================================================================

PROMPT ====================================================================;
PROMPT 1. Complete Booking Summary with Financial Details;
PROMPT ====================================================================;

SELECT 
    b.booking_id,
    t.first_name || ' ' || t.last_name AS tourist_name,
    t.country,
    p.package_name,
    p.destination,
    b.number_of_guests,
    b.total_amount,
    b.booking_status,
    NVL(pay.payment_method, 'N/A') AS payment_method,
    NVL(pay.payment_status, 'UNPAID') AS payment_status
FROM BOOKING b
JOIN TOURIST t ON b.tourist_id = t.tourist_id
JOIN TOUR_PACKAGE p ON b.package_id = p.package_id
LEFT JOIN PAYMENT pay ON b.booking_id = pay.booking_id
ORDER BY b.booking_id DESC;

PROMPT ====================================================================;
PROMPT 2. Revenue Summary by Tour Package;
PROMPT ====================================================================;

SELECT 
    p.package_name,
    COUNT(b.booking_id) AS total_bookings,
    SUM(b.number_of_guests) AS total_tourists,
    NVL(SUM(pay.amount_paid), 0) AS total_revenue_usd
FROM TOUR_PACKAGE p
LEFT JOIN BOOKING b ON p.package_id = b.package_id AND b.booking_status = 'CONFIRMED'
LEFT JOIN PAYMENT pay ON b.booking_id = pay.booking_id AND pay.payment_status = 'COMPLETED'
GROUP BY p.package_name
ORDER BY total_revenue_usd DESC;

PROMPT ====================================================================;
PROMPT 3. Inspect Audit Logs Generated by Triggers;
PROMPT ====================================================================;

SELECT 
    audit_id,
    operation_type,
    performed_by,
    TO_CHAR(performed_at, 'YYYY-MM-DD HH24:MI:SS') AS timestamp,
    details
FROM AUDIT_LOGS
ORDER BY audit_id ASC;